### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chryton** [chryton/Collection-Artificer#1]
## Current:
- [ ] Add Update method
- [ ] Add Delete method
- [ ] Basic styling (possibly Foundation)
## Future:
- [x] ~~Replace MTGImage links (this may require a major rewrite to be able to use Multiverse ID on a per card basis. Maybe some day MTGImage will come back...)~~ (currently this is using the Gatherer Name link)
- [ ] Actual styling and UI
